# Generated by Django 5.0.8 on 2026-04-16 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_discountcode_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discountcode',
            name='payments_dc_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='discountcode',
            name='payments_dc_valid_until_idx',
        ),
        migrations.AddField(
            model_name='plan',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
