# Generated by Django 5.0.8 on 2025-03-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookusercredentials',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
