# Generated by Django 5.0.8 on 2025-02-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookusercredentials',
            name='session_cookie',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
