# Generated by Django 5.0.8 on 2025-02-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0002_facebookusercredentials'),
        ('VehicleListing', '0002_vehiclelisting_status_facebooklisting'),
    ]

    operations = [
    ]
