# Generated by Django 5.0.8 on 2025-03-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0003_vehiclelisting_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookusercredentials',
            old_name='email',
            new_name='username',
        ),
    ]
