# Generated by Django 5.0.8 on 2025-02-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0004_rename_gumtree_profile_id_vehiclelisting_seller_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='transmission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
