# Generated by Django 5.0.8 on 2025-02-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0005_alter_vehiclelisting_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookprofilelisting',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='gumtreeprofilelisting',
            name='error_message',
        ),
        migrations.AddField(
            model_name='facebookprofilelisting',
            name='profile_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gumtreeprofilelisting',
            name='profile_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='facebook_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleListing.facebookprofilelisting'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='gumtree_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleListing.gumtreeprofilelisting'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='gumtree_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VehicleListing.listingurl'),
        ),
        migrations.AlterField(
            model_name='facebooklisting',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingurl',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='body_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='variant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
