# Generated by Django 5.0.8 on 2025-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0005_remove_facebookusercredentials_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='renew_date',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
