# Generated by Django 5.0.8 on 2025-02-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0006_remove_facebookprofilelisting_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
