# Generated by Django 5.0.8 on 2025-02-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0007_alter_vehiclelisting_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofilelisting',
            name='total_listings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gumtreeprofilelisting',
            name='total_listings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
