# Generated by Django 5.0.8 on 2025-04-22 06:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0007_invoice_relistingfacebooklisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookusercredentials',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookusercredentials',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5),
        ),
    ]
