# Generated by Django 5.0.8 on 2025-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0008_facebookusercredentials_retry_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='renew_date',
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='is_relist',
            field=models.BooleanField(default=False),
        ),
    ]
