# Generated by Django 5.0.8 on 2025-02-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0008_facebookprofilelisting_total_listings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofilelisting',
            name='processed_listings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gumtreeprofilelisting',
            name='processed_listings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
