# Generated by Django 5.0.8 on 2025-04-23 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0009_remove_vehiclelisting_renew_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relistingfacebooklisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relistingfacebooklisting',
            name='last_relisting_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relistingfacebooklisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
