# Generated by Django 5.0.8 on 2025-04-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0010_relistingfacebooklisting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relistingfacebooklisting',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
