# Generated by Django 5.0.8 on 2025-05-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0011_relistingfacebooklisting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingurl',
            name='listing_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
