# Generated by Django 5.0.8 on 2025-05-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0012_listingurl_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookusercredentials',
            name='status_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
