# Generated by Django 5.0.8 on 2025-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0013_facebookusercredentials_status_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
    ]
