# Generated by Django 5.0.8 on 2025-05-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0014_vehiclelisting_has_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='listed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
