# Generated by Django 5.0.8 on 2025-07-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0015_vehiclelisting_listed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
