# Generated by Django 5.0.8 on 2025-12-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0016_vehiclelisting_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='sales',
            field=models.BooleanField(default=False),
        ),
    ]
