# Generated by Django 5.0.8 on 2026-04-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0021_vehiclelisting_stripe_overage_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
