# Generated by Django 5.0.8 on 2026-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0032_vehiclelisting_mileage_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='total_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
