# Generated by Django 5.0.8 on 2026-07-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0033_vehiclelisting_total_view_count'),
        ('VehicleListing', '0033_vehiclelisting_vin'),
    ]

    operations = [
    ]
