# Generated by Django 5.0.8 on 2026-07-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0034_merge_20260710_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
