# Generated by Django 5.0.8 on 2026-07-18 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0036_facebooklistingsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facebooklistingsnapshot',
            name='unique_user_fb_listing',
        ),
        migrations.RenameIndex(
            model_name='facebooklistingsnapshot',
            new_name='VehicleList_user_id_1ab23e_idx',
            old_name='vl_fbsnap_user_synced_idx',
        ),
        migrations.RenameIndex(
            model_name='facebooklistingsnapshot',
            new_name='VehicleList_user_id_2ddb85_idx',
            old_name='vl_fbsnap_user_aged_idx',
        ),
        migrations.AlterUniqueTogether(
            name='facebooklistingsnapshot',
            unique_together={('user', 'fb_listing_id')},
        ),
    ]
