# Generated by Django 5.0.8 on 2026-07-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0038_unpublishedlistingsnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='unpublishedlistingsnapshot',
            new_name='VehicleList_user_id_bc489e_idx',
            old_name='vl_unpub_user_synced_idx',
        ),
        migrations.RenameIndex(
            model_name='unpublishedlistingsnapshot',
            new_name='VehicleList_user_id_1d5644_idx',
            old_name='vl_unpub_user_reason_idx',
        ),
    ]
