# Generated by Django 5.0.8 on 2026-08-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0044_fbverificationevent'),
        ('VehicleListing', '0046_vehicle_variant'),
    ]

    operations = [
    ]
