from django.urls import path
from .views import (
    get_user_gumtree_profile_vehicle_listings,
    update_vehicle_listing_listed_on,
    update_vehicle_listing_is_changed,
    update_vehicle_listing_facebook_id,
    get_old_vehicle_listings,
    get_user_custom_domain_profile_vehicle_listings,
    get_custom_domain_profile_listings,
    custom_domain_image_proxy,
    get_all_products,
    get_products_by_category,
    get_product_by_slug,
    increment_product_view_count,
    get_latest_arrivals,
)

urlpatterns = [
    # path('import/', import_url_from_gumtree, name='import_url_from_gumtree'),
    # path('gumtree/', all_vehicle_listing, name='all_vehicle_listing'),
    # path('listing_urls/', ListingUrlViewSet.as_view({'get': 'list' , 'post': 'create'}), name='listing_url'),
    # path('listing_urls/<int:pk>/', ListingUrlViewSet.as_view({'get': 'retrieve',  'patch': 'update', 'delete': 'destroy'}), name='listing_url_detail'),
    # path('', VehicleListingViewSet.as_view({'get': 'list' , 'post': 'create'}), name='vehicle_listing'),
    # path('<int:pk>/', VehicleListingViewSet.as_view({'get': 'retrieve',  'patch': 'update', 'delete': 'destroy'}), name='vehicle_listing_detail'),
    # path('facebook_user/', FacebookUserCredentialsViewSet.as_view({'get': 'list' , 'post': 'create'}), name='facebook_user'),
    # path('facebook_user/<int:pk>/', FacebookUserCredentialsViewSet.as_view({'get': 'retrieve',  'patch': 'update', 'delete': 'destroy'}), name='facebook_user_detail'),
    # path('gumtree_profile_listings/', get_gumtree_profile_listings, name='get_gumtree_profile_listings'),
    # path('facebook_profile_listings/', facebook_profile_listings, name='facebook_profile_listings'),
    # path('gumtree_profile_listings_details/', GumtreeProfileListingViewSet.as_view({'get': 'list' , 'post': 'create'}), name='gumtree_profile_listings'),
    # path('gumtree_profile_listings_details/<int:pk>/', GumtreeProfileListingViewSet.as_view({'get': 'retrieve',  'patch': 'update', 'delete': 'destroy'}), name='gumtree_profile_listings_detail'),
    # path('facebook_profile_listings_details/', FacebookProfileListingViewSet.as_view({'get': 'list' , 'post': 'create'}), name='facebook_profile_listings'),
    # path('facebook_profile_listings_details/<int:pk>/', FacebookProfileListingViewSet.as_view({'get': 'retrieve',  'patch': 'update', 'delete': 'destroy'}), name='facebook_profile_listings_detail'),
    # path('monthly_report/', get_montly_listings_report, name='get_montly_listings_report'),
    # path('facebook_session_status/', get_facebook_session_status, name='get_facebook_session_status'),
    path('gumtree-listings/', get_user_gumtree_profile_vehicle_listings, name='get_user_gumtree_profile_vehicle_listings'),
    path('custom-domain-listings/', get_user_custom_domain_profile_vehicle_listings, name='get_user_custom_domain_profile_vehicle_listings'),
    path('custom-domain-profile-listings/', get_custom_domain_profile_listings, name='get_custom_domain_profile_listings'),
    path('custom-domain-image/', custom_domain_image_proxy, name='custom_domain_image_proxy'),
    path('listed-on/', update_vehicle_listing_listed_on, name='update_vehicle_listing_listed_on'),
    path('mark-changed/', update_vehicle_listing_is_changed, name='update_vehicle_listing_is_changed'),
    path('facebook-id/', update_vehicle_listing_facebook_id, name='update_vehicle_listing_facebook_id'),
    path('old-listings/', get_old_vehicle_listings, name='get_old_vehicle_listings'),
    path('products/', get_all_products, name='get_all_products'),
    path('categories/<str:category>/', get_products_by_category, name='get_products_by_category'),
    path('vehicle/<str:name>-<int:vehicle_id>/', get_product_by_slug, name='get_product_by_slug'),
    path('vehicle/<int:vehicle_id>/increment-view/', increment_product_view_count, name='increment_product_view_count'),
    path('latest-arrivals/', get_latest_arrivals, name='get_latest_arrivals'),
]
