# Generated by Django 5.0.8 on 2025-04-22 11:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_user_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5),
        ),
    ]
