# Generated by Django 5.0.8 on 2025-04-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rate',
        ),
    ]
