# Generated by Django 5.0.8 on 2025-05-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_facebook_listing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
