# Generated by Django 5.0.8 on 2025-05-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_facebook_listing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_images_check_status_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
