# Generated by Django 5.0.8 on 2025-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_last_images_check_status_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_listing_count',
            field=models.IntegerField(default=0),
        ),
    ]
