# Generated by Django 5.2.2 on 2025-08-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_daily_listing_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_delete_listing_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
