# Generated by Django 5.0.8 on 2026-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_listing_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('trial_expired', 'Trial Expired'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
    ]
