# Generated by Django 5.0.8 on 2026-05-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dnacarsales_dealership_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
